- name: Playbook
  hosts: vm3
  become: 'yes'
  tasks:
    - name:  Install  nginx
      apt:
        pkg:
          - nginx
        state: present
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
